#
# launcher Makefile for x86 Linux
#
#

HL_SRC_DIR=$(SOURCE_DIR)/cl_dll
HL_SERVER_SRC_DIR=$(SOURCE_DIR)/dlls
GAME_SHARED_SRC_DIR=$(SOURCE_DIR)/game_shared
PM_SHARED_SRC_DIR=$(SOURCE_DIR)/pm_shared

HL1_OBJ_DIR=$(BUILD_OBJ_DIR)/hl1_client
PUBLIC_OBJ_DIR=$(HL1_OBJ_DIR)/public
COMMON_OBJ_DIR=$(HL1_OBJ_DIR)/common
GAME_SHARED_OBJ_DIR=$(HL1_OBJ_DIR)/game_shared
HL1_SERVER_OBJ_DIR=$(HL1_OBJ_DIR)/server
PM_SHARED_OBJ_DIR=$(HL1_OBJ_DIR)/pm_shared
HL_OUTPUT_DIR=$(SOURCE_DIR)/../game/valve

CFLAGS=$(BASE_CFLAGS) $(ARCH_CFLAGS) -DCLIENT_DLL -DCLIENT_WEAPONS -DHL_DLL -I/usr/include/malloc -D_snwprintf=swprintf \
		 -DDISABLE_JUMP_ORIGIN -DDISABLE_VEC_ORIGIN
INCLUDEDIRS=-I$(HL_SRC_DIR) -I$(HL_SRC_DIR)/hud -I$(HL_SRC_DIR)/studio -I$(HL_SRC_DIR)/input -I$(HL_SRC_DIR)/core -I$(HL_SRC_DIR)/render -I$(HL_SRC_DIR)/entities -I$(HL_SRC_DIR)/hl -I$(HL_SRC_DIR)/systems -I$(HL_SRC_DIR)/events -I../dlls -I../dlls/core -I../dlls/weapons -I../tfc -I$(COMMON_SRC_DIR) -I$(PUBLIC_SRC_DIR) -I../pm_shared -I../engine -I../utils/vgui/include -I ../game_shared -I../external
ifeq ($(OS),Darwin)
LDFLAGS=$(SHLIBLDFLAGS) $(CPP_LIB) -framework Carbon $(CFG)/vgui.dylib -L. -lSDL2-2.0.0
else
LDFLAGS=$(SHLIBLDFLAGS) $(CPP_LIB) -L$(CFG) vgui.so -L. -lSDL2
endif

DO_CC=$(CPLUS) $(INCLUDEDIRS) $(CFLAGS) -o $@ -c $<
DO_PUBLIC_CC=$(CPLUS) $(COMMON_INCLUDEDIRS) $(CFLAGS) $(SHLIBCFLAGS) -o $@ -c $<
DO_COMMON_CC=$(CPLUS) $(INCLUDEDIRS)  $(CFLAGS) $(SHLIBCFLAGS) -o $@ -c $<
DO_PM_SHARED_CC=$(CC) $(INCLUDEDIRS)  $(CFLAGS) $(SHLIBCFLAGS) -o $@ -c $<

#####################################################################

HL1_OBJS = \
	$(HL1_OBJ_DIR)/hud/hud_spectator.o \
	$(HL1_OBJ_DIR)/hud/hud_weapon_selection.o \
	$(HL1_OBJ_DIR)/events/ev_hldm.o \
	$(HL1_OBJ_DIR)/events/ev_bullets.o \
	$(HL1_OBJ_DIR)/events/ev_energy.o \
	$(HL1_OBJ_DIR)/events/ev_explosives.o \
	$(HL1_OBJ_DIR)/hl/hl_baseentity.o \
	$(HL1_OBJ_DIR)/hl/hl_events.o \
	$(HL1_OBJ_DIR)/hl/hl_objects.o \
	$(HL1_OBJ_DIR)/hl/hl_weapons.o \
	$(HL1_OBJ_DIR)/hl/client_weapon_manager.o \
	$(HL1_OBJ_DIR)/events/event_registry.o \
	$(HL1_OBJ_DIR)/hud/hud.o \
	$(HL1_OBJ_DIR)/hud/hud_ammo.o \
	$(HL1_OBJ_DIR)/hud/battery.o \
	$(HL1_OBJ_DIR)/core/cdll_int.o \
	$(HL1_OBJ_DIR)/hl/com_weapons.o \
	$(HL1_OBJ_DIR)/hud/death.o \
	$(HL1_OBJ_DIR)/systems/demo.o \
	$(HL1_OBJ_DIR)/entities/entity.o \
	$(HL1_OBJ_DIR)/entities/entity_visual_registry.o \
	$(HL1_OBJ_DIR)/events/ev_common.o \
	$(HL1_OBJ_DIR)/events/events.o \
	$(HL1_OBJ_DIR)/hud/flashlight.o \
	$(HL1_OBJ_DIR)/hud/geiger.o \
	$(HL1_OBJ_DIR)/hud/health.o \
	$(HL1_OBJ_DIR)/hud/hud_bench.o \
	$(HL1_OBJ_DIR)/hud/hud_benchtrace.o \
	$(HL1_OBJ_DIR)/hud/hud_msg.o \
	$(HL1_OBJ_DIR)/hud/hud_redraw.o \
	$(HL1_OBJ_DIR)/hud/hud_registry.o \
	$(HL1_OBJ_DIR)/hud/hud_update.o \
	$(HL1_OBJ_DIR)/render/interpolation.o \
	$(HL1_OBJ_DIR)/hud/menu.o \
	$(HL1_OBJ_DIR)/hud/message.o \
	$(HL1_OBJ_DIR)/hud/saytext.o \
	$(HL1_OBJ_DIR)/hud/status_icons.o \
	$(HL1_OBJ_DIR)/hud/statusbar.o \
	$(HL1_OBJ_DIR)/hud/text_message.o \
	$(HL1_OBJ_DIR)/hud/train.o \
	$(HL1_OBJ_DIR)/studio/GameStudioModelRenderer.o \
	$(HL1_OBJ_DIR)/input/in_camera.o \
	$(HL1_OBJ_DIR)/input/input.o \
	$(HL1_OBJ_DIR)/input/inputw32.o \
	$(HL1_OBJ_DIR)/input/input_hardware.o \
	$(HL1_OBJ_DIR)/studio/studio_util.o \
	$(HL1_OBJ_DIR)/studio/StudioModelRenderer.o \
	$(HL1_OBJ_DIR)/render/tri.o \
	$(HL1_OBJ_DIR)/core/util.o \
	$(HL1_OBJ_DIR)/render/view.o \
	$(HL1_OBJ_DIR)/render/view_camera.o \
	$(HL1_OBJ_DIR)/render/view_bob.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_int.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_ClassMenuPanel.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_ControlConfigPanel.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_CustomObjects.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_MOTDWindow.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_SchemeManager.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_ScorePanel.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_ServerBrowser.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_TeamFortressViewport.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_viewport_menus.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_viewport_messages.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_CommandMenuPanel.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_SpectatorPanel.o \
	$(HL1_OBJ_DIR)/VGUI/vgui_TeamMenuPanel.o \
	$(HL1_OBJ_DIR)/hud/voice_status.o \
	$(HL1_OBJ_DIR)/hud/hud_servers.o \


DLL_OBJS = \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_crossbow.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_crowbar.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_egon.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_gauss.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_handgrenade.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_hornetgun.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_mp5.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_python.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_rpg.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_satchel.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_shotgun.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_snark.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_glock.o \
	$(HL1_SERVER_OBJ_DIR)/weapons/weapon_tripmine.o \


PUBLIC_OBJS = \
	$(PUBLIC_OBJ_DIR)/interface.o \

COMMON_OBJS = \
	$(COMMON_OBJ_DIR)/parsemsg.o \

GAME_SHARED_OBJS = \
	$(GAME_SHARED_OBJ_DIR)/vgui_checkbutton2.o \
	$(GAME_SHARED_OBJ_DIR)/vgui_grid.o \
	$(GAME_SHARED_OBJ_DIR)/vgui_helpers.o \
	$(GAME_SHARED_OBJ_DIR)/vgui_listbox.o \
	$(GAME_SHARED_OBJ_DIR)/vgui_loadtga.o \
	$(GAME_SHARED_OBJ_DIR)/vgui_scrollbar2.o \
	$(GAME_SHARED_OBJ_DIR)/vgui_slider2.o \
	$(GAME_SHARED_OBJ_DIR)/voice_banmgr.o \

PM_SHARED_OBJS = \
	$(PM_SHARED_OBJ_DIR)/pm_debug.o \
	$(PM_SHARED_OBJ_DIR)/pm_shared.o \
	$(PM_SHARED_OBJ_DIR)/pm_step.o \
	$(PM_SHARED_OBJ_DIR)/pm_move_ground.o \
	$(PM_SHARED_OBJ_DIR)/pm_move_air.o \
	$(PM_SHARED_OBJ_DIR)/pm_move_water.o \
	$(PM_SHARED_OBJ_DIR)/pm_ladders.o \
	$(PM_SHARED_OBJ_DIR)/pm_duck.o \
	$(PM_SHARED_OBJ_DIR)/pm_hull.o \
	$(PM_SHARED_OBJ_DIR)/pm_math.o \



all: client.$(SHLIBEXT)

client.$(SHLIBEXT): $(HL1_OBJS) $(PUBLIC_OBJS) $(COMMON_OBJS) $(GAME_SHARED_OBJS) $(DLL_OBJS) $(PM_SHARED_OBJS)
	$(CLINK) -o $(BUILD_DIR)/$@ $(HL1_OBJS) $(PUBLIC_OBJS) $(COMMON_OBJS) $(GAME_SHARED_OBJS) $(DLL_OBJS) $(PM_SHARED_OBJS) $(LDFLAGS) $(CPP_LIB)
ifeq ($(CREATE_OUTPUT_DIRS),1)
	mkdir -p $(HL_OUTPUT_DIR)/cl_dlls
endif
	$(P4_EDIT_START) $(HL_OUTPUT_DIR)/cl_dlls/$@ $(P4_EDIT_END)
	cp $(BUILD_DIR)/$@  $(HL_OUTPUT_DIR)/cl_dlls
	./gendbg.sh $(HL_OUTPUT_DIR)/cl_dlls/client.$(SHLIBEXT)

$(HL1_OBJ_DIR):
	mkdir -p $(HL1_OBJ_DIR)
	mkdir -p $(HL1_OBJ_DIR)/hud
	mkdir -p $(HL1_OBJ_DIR)/hl
	mkdir -p $(HL1_OBJ_DIR)/studio
	mkdir -p $(HL1_OBJ_DIR)/input
	mkdir -p $(HL1_OBJ_DIR)/core
	mkdir -p $(HL1_OBJ_DIR)/render
	mkdir -p $(HL1_OBJ_DIR)/entities
	mkdir -p $(HL1_OBJ_DIR)/dlls/wpn_shared
	mkdir -p $(HL1_OBJ_DIR)/VGUI
	mkdir -p $(HL1_OBJ_DIR)/systems
	mkdir -p $(HL1_OBJ_DIR)/events

$(HL1_SERVER_OBJ_DIR):
	mkdir -p $(HL1_SERVER_OBJ_DIR)
	mkdir -p $(HL1_SERVER_OBJ_DIR)/wpn_shared
	mkdir -p $(HL1_SERVER_OBJ_DIR)/weapons

$(HL1_SERVER_OBJ_DIR)/weapons:
	mkdir -p $(HL1_SERVER_OBJ_DIR)/weapons

$(PUBLIC_OBJ_DIR):
	mkdir -p $(PUBLIC_OBJ_DIR)

$(COMMON_OBJ_DIR):
	mkdir -p $(COMMON_OBJ_DIR)

$(GAME_SHARED_OBJ_DIR):
	mkdir -p $(GAME_SHARED_OBJ_DIR)

$(PM_SHARED_OBJ_DIR):
	mkdir -p $(PM_SHARED_OBJ_DIR)



$(HL1_OBJ_DIR)/hud/%.o: $(HL_SRC_DIR)/hud/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)/hud),  $(HL1_OBJ_DIR)/hud)
	$(DO_CC)

$(HL1_OBJ_DIR)/%.o: $(HL_SRC_DIR)/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)

$(HL1_SERVER_OBJ_DIR)/%.o: $(HL_SERVER_SRC_DIR)/%.cpp $(filter-out $(wildcard  $(HL1_SERVER_OBJ_DIR)),  $(HL1_SERVER_OBJ_DIR))
	$(DO_CC)

$(HL1_SERVER_OBJ_DIR)/weapons/%.o: $(HL_SERVER_SRC_DIR)/weapons/%.cpp $(filter-out $(wildcard  $(HL1_SERVER_OBJ_DIR)/weapons),  $(HL1_SERVER_OBJ_DIR)/weapons)
	$(DO_CC)

$(HL1_OBJ_DIR)/hl/%.o: $(HL_SRC_DIR)/hl/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)/hl),  $(HL1_OBJ_DIR)/hl)
	$(DO_CC)


$(HL1_OBJ_DIR)/studio/%.o: $(HL_SRC_DIR)/studio/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)

$(HL1_OBJ_DIR)/render/%.o: $(HL_SRC_DIR)/render/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)

$(HL1_OBJ_DIR)/entities/%.o: $(HL_SRC_DIR)/entities/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)

$(HL1_OBJ_DIR)/input/%.o: $(HL_SRC_DIR)/input/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)

$(HL1_OBJ_DIR)/%.o: $(HL_SRC_DIR)/dlls/wpn_shared/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)


$(PUBLIC_OBJ_DIR)/%.o : $(PUBLIC_SRC_DIR)/%.cpp $(filter-out $(wildcard  $(PUBLIC_OBJ_DIR)),  $(PUBLIC_OBJ_DIR))
	$(DO_PUBLIC_CC)

$(COMMON_OBJ_DIR)/%.o : $(COMMON_SRC_DIR)/%.cpp $(filter-out $(wildcard  $(COMMON_OBJ_DIR)),  $(COMMON_OBJ_DIR))
	$(DO_COMMON_CC)

$(GAME_SHARED_OBJ_DIR)/%.o : $(GAME_SHARED_SRC_DIR)/%.cpp $(filter-out $(wildcard  $(GAME_SHARED_OBJ_DIR)),  $(GAME_SHARED_OBJ_DIR))
	$(DO_COMMON_CC)

$(PM_SHARED_OBJ_DIR)/%.o : $(PM_SHARED_SRC_DIR)/%.c $(filter-out $(wildcard  $(PM_SHARED_OBJ_DIR)),  $(PM_SHARED_OBJ_DIR))
	$(DO_PM_SHARED_CC)

clean:
	-rm -rf $(HL1_OBJ_DIR)
	-rm -f client.$(SHLIBEXT)

$(HL1_OBJ_DIR)/VGUI/%.o: $(HL_SRC_DIR)/vgui/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)

$(HL1_OBJ_DIR)/core/%.o: $(HL_SRC_DIR)/core/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)),  $(HL1_OBJ_DIR))
	$(DO_CC)

$(HL1_OBJ_DIR)/systems/%.o: $(HL_SRC_DIR)/systems/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)/systems),  $(HL1_OBJ_DIR)/systems)
	$(DO_CC)

$(HL1_OBJ_DIR)/events/%.o: $(HL_SRC_DIR)/events/%.cpp $(filter-out $(wildcard  $(HL1_OBJ_DIR)/events),  $(HL1_OBJ_DIR)/events)
	$(DO_CC)
