#
# Behavioral Equivalence Verification - Unit Test Suite Makefile for Linux
#

HLDLL_SRC_DIR=$(SOURCE_DIR)/dlls
HLCORE_SRC_DIR=$(HLDLL_SRC_DIR)/core
TESTS_SRC_DIR=$(SOURCE_DIR)/tests
EXTERNAL_SRC_DIR=$(SOURCE_DIR)/external

TESTS_OBJ_DIR=$(BUILD_OBJ_DIR)/tests
PM_OBJ_DIR=$(BUILD_OBJ_DIR)/tests_pm

TESTS_INCLUDEDIRS=-I$(SOURCE_DIR) -I$(TESTS_SRC_DIR) -I$(EXTERNAL_SRC_DIR)/catch2 -I$(HLDLL_SRC_DIR) -I$(HLCORE_SRC_DIR) -I$(HLDLL_SRC_DIR)/weapons -I$(SOURCE_DIR)/cl_dll -I$(ENGINE_SRC_DIR) -I$(COMMON_SRC_DIR) -I$(PM_SRC_DIR) -I$(GAME_SHARED_SRC_DIR) -I$(PUBLIC_SRC_DIR)

TESTS_CFLAGS=$(BASE_CFLAGS) $(ARCH_CFLAGS) -std=c++14 -DHL_TESTS -DVALVE_DLL -DCATCH_AMALGAMATED_CUSTOM_MAIN
PM_CFLAGS=$(BASE_CFLAGS) $(ARCH_CFLAGS)

LDFLAGS=-lm -ldl -lstdc++ -lpthread

DO_TESTS_CXX=$(CPLUS) $(TESTS_INCLUDEDIRS) $(TESTS_CFLAGS) -o $@ -c $<
DO_PM_CC=$(CC) $(TESTS_INCLUDEDIRS) $(PM_CFLAGS) -o $@ -c $<

TEST_OBJS = \
	$(TESTS_OBJ_DIR)/catch_amalgamated.o \
	$(TESTS_OBJ_DIR)/mock_engine.o \
	$(TESTS_OBJ_DIR)/mock_client_engine.o \
	$(TESTS_OBJ_DIR)/test_main.o \
	$(TESTS_OBJ_DIR)/test_pm_movement.o \
	$(TESTS_OBJ_DIR)/test_combat.o \
	$(TESTS_OBJ_DIR)/test_abi_layout.o \
	$(TESTS_OBJ_DIR)/test_saverestore.o \
	$(TESTS_OBJ_DIR)/test_weapon_pipeline.o \
	$(TESTS_OBJ_DIR)/test_item_registry.o \
	$(TESTS_OBJ_DIR)/test_ai_factions.o \
	$(TESTS_OBJ_DIR)/test_gamerules_skill.o \
	$(TESTS_OBJ_DIR)/test_gameplay_hooks.o \
	$(TESTS_OBJ_DIR)/test_client_lifecycle.o \
	$(TESTS_OBJ_DIR)/test_client_studio.o \
	$(TESTS_OBJ_DIR)/test_studio_transform.o \
	$(TESTS_OBJ_DIR)/test_level_transition.o \
	$(TESTS_OBJ_DIR)/weapon_registry.o \
	$(TESTS_OBJ_DIR)/item_registry.o \
	$(TESTS_OBJ_DIR)/monster_relationship_manager.o \
	$(TESTS_OBJ_DIR)/talk_companion_registry.o \
	$(TESTS_OBJ_DIR)/nodes_graph.o \
	$(TESTS_OBJ_DIR)/nodes_routing.o \
	$(TESTS_OBJ_DIR)/nodes_links.o \
	$(TESTS_OBJ_DIR)/gamerules_factory.o \
	$(TESTS_OBJ_DIR)/skill_manager.o \
	$(TESTS_OBJ_DIR)/skill.o \
	$(TESTS_OBJ_DIR)/user_message_registry.o \
	$(TESTS_OBJ_DIR)/client_weapon_manager.o \
	$(TESTS_OBJ_DIR)/event_registry.o \
	$(TESTS_OBJ_DIR)/hud_registry.o \
	$(TESTS_OBJ_DIR)/entity_visual_registry.o \
	$(TESTS_OBJ_DIR)/test_hud_registry.o \
	$(TESTS_OBJ_DIR)/test_effects_beams.o \
	$(TESTS_OBJ_DIR)/test_crash_handler.o \
	$(TESTS_OBJ_DIR)/test_triggers.o \
	$(TESTS_OBJ_DIR)/test_player_customization.o \
	$(TESTS_OBJ_DIR)/test_ai_navigation.o \
	$(TESTS_OBJ_DIR)/client_customization.o \
	$(TESTS_OBJ_DIR)/chargers.o \
	$(TESTS_OBJ_DIR)/effects_beams.o \
	$(TESTS_OBJ_DIR)/triggers_audio.o \
	$(TESTS_OBJ_DIR)/crash_handler.o

PM_OBJS = \
	$(PM_OBJ_DIR)/pm_shared.o \
	$(PM_OBJ_DIR)/pm_step.o \
	$(PM_OBJ_DIR)/pm_move_ground.o \
	$(PM_OBJ_DIR)/pm_move_air.o \
	$(PM_OBJ_DIR)/pm_move_water.o \
	$(PM_OBJ_DIR)/pm_ladders.o \
	$(PM_OBJ_DIR)/pm_duck.o \
	$(PM_OBJ_DIR)/pm_hull.o \
	$(PM_OBJ_DIR)/pm_math.o \
	$(PM_OBJ_DIR)/pm_debug.o

all: dirs $(BUILD_DIR)/hl_tests $(BUILD_DIR)/smoke_test_client

dirs:
	-mkdir -p $(BUILD_DIR)
	-mkdir -p $(TESTS_OBJ_DIR)
	-mkdir -p $(PM_OBJ_DIR)

$(BUILD_DIR)/hl_tests: $(TEST_OBJS) $(PM_OBJS)
	$(CPLUS) -m32 -o $@ $(TEST_OBJS) $(PM_OBJS) $(LDFLAGS)

$(BUILD_DIR)/smoke_test_client: $(TESTS_OBJ_DIR)/smoke_test_client.o
	$(CPLUS) -m32 -o $@ $< -ldl -lm -lpthread

$(TESTS_OBJ_DIR)/catch_amalgamated.o: $(EXTERNAL_SRC_DIR)/catch2/catch_amalgamated.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/%.o: $(TESTS_SRC_DIR)/%.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/weapon_registry.o: $(HLDLL_SRC_DIR)/weapons/weapon_registry.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/item_registry.o: $(HLDLL_SRC_DIR)/items/item_registry.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/monster_relationship_manager.o: $(HLDLL_SRC_DIR)/ai/monster_relationship_manager.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/talk_companion_registry.o: $(HLDLL_SRC_DIR)/ai/talk_companion_registry.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/nodes_graph.o: $(HLDLL_SRC_DIR)/ai/nodes_graph.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/nodes_routing.o: $(HLDLL_SRC_DIR)/ai/nodes_routing.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/nodes_links.o: $(HLDLL_SRC_DIR)/ai/nodes_links.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/gamerules_factory.o: $(HLDLL_SRC_DIR)/gameplay/gamerules_factory.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/skill_manager.o: $(HLCORE_SRC_DIR)/skill_manager.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/skill.o: $(HLCORE_SRC_DIR)/skill.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/client_weapon_manager.o: $(SOURCE_DIR)/cl_dll/hl/client_weapon_manager.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/event_registry.o: $(SOURCE_DIR)/cl_dll/events/event_registry.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/hud_registry.o: $(SOURCE_DIR)/cl_dll/hud/hud_registry.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/user_message_registry.o: $(HLCORE_SRC_DIR)/user_message_registry.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/client_customization.o: $(HLCORE_SRC_DIR)/client_customization.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/entity_visual_registry.o: $(SOURCE_DIR)/cl_dll/entities/entity_visual_registry.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/chargers.o: $(HLDLL_SRC_DIR)/systems/chargers.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/effects_beams.o: $(HLDLL_SRC_DIR)/systems/effects_beams.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/triggers_audio.o: $(HLDLL_SRC_DIR)/systems/triggers_audio.cpp | dirs
	$(DO_TESTS_CXX)

$(TESTS_OBJ_DIR)/crash_handler.o: $(HLDLL_SRC_DIR)/systems/crash_handler.cpp | dirs
	$(DO_TESTS_CXX)

$(PM_OBJ_DIR)/%.o: $(PM_SRC_DIR)/%.c | dirs
	$(DO_PM_CC)

clean:
	-rm -rf $(TESTS_OBJ_DIR)
	-rm -rf $(PM_OBJ_DIR)
	-rm -f $(BUILD_DIR)/hl_tests $(BUILD_DIR)/smoke_test_client

test: all
	$(BUILD_DIR)/hl_tests
