#
# HL game library Makefile for x86 Linux
#
# Feb 2001 by Leon Hartwig (hartwig@valvesoftware.com)
#

HLDLL_SRC_DIR=$(SOURCE_DIR)/dlls
HLCORE_SRC_DIR=$(HLDLL_SRC_DIR)/core
HLWPN_SRC_DIR=$(HLDLL_SRC_DIR)/wpn_shared

HLDLL_OBJ_DIR=$(BUILD_OBJ_DIR)/hldll
HLCORE_OBJ_DIR=$(HLDLL_OBJ_DIR)/core
HLWPN_OBJ_DIR=$(HLDLL_OBJ_DIR)/wpn_shared
PM_OBJ_DIR=$(HLDLL_OBJ_DIR)/pm_shared
GAME_SHARED_OBJ_DIR=$(HLDLL_OBJ_DIR)/game_shared
HL_OUTPUT_DIR=$(SOURCE_DIR)/../game/valve

#CFLAGS=$(BASE_CFLAGS) $(ARCH_CFLAGS) $(SHLIBCFLAGS) -DCLIENT_WEAPONS
CFLAGS=$(BASE_CFLAGS)  $(ARCH_CFLAGS)  -DCLIENT_WEAPONS
#-O3 -ffast-math -fno-strength-reduce

HLDLL_INCLUDEDIRS=-I$(HLDLL_SRC_DIR) -I$(HLCORE_SRC_DIR) -I$(HLDLL_SRC_DIR)/weapons -I$(ENGINE_SRC_DIR) -I$(COMMON_SRC_DIR) -I$(PM_SRC_DIR) -I$(GAME_SHARED_SRC_DIR) -I$(PUBLIC_SRC_DIR) -I$(SOURCE_DIR)/public -I../public
HLWPN_INCLUDEDIRS=-I$(HLDLL_SRC_DIR) -I$(HLCORE_SRC_DIR) -I$(HLDLL_SRC_DIR)/weapons -I$(ENGINE_SRC_DIR) -I$(COMMON_SRC_DIR) -I$(PM_SRC_DIR) -I$(GAME_SHARED_SRC_DIR) -I$(PUBLIC_SRC_DIR) -I$(SOURCE_DIR)/public -I../public
PM_INCLUDEDIRS=-I$(COMMON_SRC_DIR)  -I$(PUBLIC_SRC_DIR) -I$(SOURCE_DIR)/public -I../public
GAME_SHARED_INCLUDEDIRS=-I$(HLDLL_SRC_DIR) -I$(HLCORE_SRC_DIR) -I$(HLDLL_SRC_DIR)/weapons -I$(ENGINE_SRC_DIR) -I$(COMMON_SRC_DIR) -I$(PM_SRC_DIR) -I$(GAME_SHARED_SRC_DIR) -I$(PUBLIC_SRC_DIR) -I$(SOURCE_DIR)/public -I../public

LDFLAGS= -lm -lstdc++

DO_HLDLL_CC=$(CC) $(HLDLL_INCLUDEDIRS) $(CFLAGS) -o $@ -c $<
DO_HLWPN_CC=$(CC) $(HLWPN_INCLUDEDIRS) $(CFLAGS) -o $@ -c $<
DO_PM_CC=$(CC) $(PM_INCLUDEDIRS) $(CFLAGS) -o $@ -c $<
DO_GAME_SHARED_CC=$(CC) $(GAME_SHARED_INCLUDEDIRS) $(CFLAGS) -o $@ -c $<

#####################################################################

HLDLL_OBJS = \
	$(HLDLL_OBJ_DIR)/monsters/aflock.o \
	$(HLDLL_OBJ_DIR)/monsters/agrunt.o \
	$(HLDLL_OBJ_DIR)/systems/airtank.o \
	$(HLCORE_OBJ_DIR)/animating.o \
	$(HLCORE_OBJ_DIR)/animation.o \
	$(HLDLL_OBJ_DIR)/monsters/aircraft_fx.o \
	$(HLDLL_OBJ_DIR)/monsters/apache.o \
	$(HLDLL_OBJ_DIR)/monsters/barnacle.o \
	$(HLDLL_OBJ_DIR)/monsters/barney.o \
	$(HLDLL_OBJ_DIR)/monsters/bigmomma.o \
	$(HLDLL_OBJ_DIR)/monsters/bloater.o \
	$(HLDLL_OBJ_DIR)/world/bmodels.o \
	$(HLDLL_OBJ_DIR)/systems/chargers.o \
	$(HLDLL_OBJ_DIR)/systems/crash_handler.o \
	$(HLDLL_OBJ_DIR)/items/items.o \
	$(HLDLL_OBJ_DIR)/items/ammo_items.o \
	$(HLDLL_OBJ_DIR)/systems/effects_shooters.o \
	$(HLDLL_OBJ_DIR)/systems/effects_screen.o \
	$(HLDLL_OBJ_DIR)/systems/effects_env.o \
	$(HLDLL_OBJ_DIR)/systems/effects_beverage.o \
	$(HLDLL_OBJ_DIR)/systems/multisource.o \
	$(HLDLL_OBJ_DIR)/systems/env_global.o \
	$(HLDLL_OBJ_DIR)/systems/env_spark.o \
	$(HLDLL_OBJ_DIR)/world/trains.o \
	$(HLDLL_OBJ_DIR)/world/trackchange.o \
	$(HLDLL_OBJ_DIR)/world/guntarget.o \
	$(HLDLL_OBJ_DIR)/world/conveyor.o \
	$(HLDLL_OBJ_DIR)/world/rotating.o \
	$(HLDLL_OBJ_DIR)/monsters/bullsquid.o \
	$(HLDLL_OBJ_DIR)/systems/buttons.o \
	$(HLCORE_OBJ_DIR)/cbase.o \
	$(HLCORE_OBJ_DIR)/combat.o \
	$(HLCORE_OBJ_DIR)/combat_damage.o \
	$(HLCORE_OBJ_DIR)/combat_gib.o \
	$(HLCORE_OBJ_DIR)/client.o \
	$(HLCORE_OBJ_DIR)/player_suit.o \
	$(HLCORE_OBJ_DIR)/player_combat.o \
	$(HLCORE_OBJ_DIR)/player_cheats.o \
	$(HLCORE_OBJ_DIR)/client_usermsg.o \
	$(HLCORE_OBJ_DIR)/user_message_registry.o \
	$(HLCORE_OBJ_DIR)/client_spectator.o \
	$(HLCORE_OBJ_DIR)/client_networking.o \
	$(HLCORE_OBJ_DIR)/client_commands.o \
	$(HLCORE_OBJ_DIR)/client_customization.o \
	$(HLDLL_OBJ_DIR)/monsters/controller.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_crossbow.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_damage.o \
	$(HLDLL_OBJ_DIR)/weapons/projectile_bolt.o \
	$(HLDLL_OBJ_DIR)/weapons/projectile_rocket.o \
	$(HLDLL_OBJ_DIR)/weapons/projectile_satchel.o \
	$(HLDLL_OBJ_DIR)/weapons/projectile_snark.o \
	$(HLDLL_OBJ_DIR)/weapons/projectile_tripmine.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_crowbar.o \
	$(HLDLL_OBJ_DIR)/ai/defaultai.o \
	$(HLDLL_OBJ_DIR)/systems/doors.o \
	$(HLDLL_OBJ_DIR)/systems/effects_beams.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_egon.o \
	$(HLDLL_OBJ_DIR)/systems/explode.o \
	$(HLDLL_OBJ_DIR)/ai/flyingmonster.o \
	$(HLDLL_OBJ_DIR)/systems/func_break.o \
	$(HLDLL_OBJ_DIR)/systems/func_tank.o \
	$(HLCORE_OBJ_DIR)/game.o \
	$(HLDLL_OBJ_DIR)/gameplay/gamerules.o \
	$(HLDLL_OBJ_DIR)/gameplay/gamerules_factory.o \
	$(HLDLL_OBJ_DIR)/monsters/gargantua.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_gauss.o \
	$(HLDLL_OBJ_DIR)/monsters/genericmonster.o \
	$(HLDLL_OBJ_DIR)/weapons/projectile_grenade.o \
	$(HLCORE_OBJ_DIR)/globals.o \
	$(HLDLL_OBJ_DIR)/monsters/gman.o \
	$(HLDLL_OBJ_DIR)/ai/h_ai.o \
	$(HLDLL_OBJ_DIR)/gameplay/h_cine.o \
	$(HLDLL_OBJ_DIR)/systems/h_cycler.o \
	$(HLDLL_OBJ_DIR)/core/h_export.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_handgrenade.o \
	$(HLDLL_OBJ_DIR)/monsters/hassassin.o \
	$(HLDLL_OBJ_DIR)/monsters/headcrab.o \
	$(HLDLL_OBJ_DIR)/monsters/hgrunt.o \
	$(HLDLL_OBJ_DIR)/monsters/hgrunt_repel.o \
	$(HLDLL_OBJ_DIR)/weapons/projectile_hornet.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_hornetgun.o \
	$(HLDLL_OBJ_DIR)/monsters/houndeye.o \
	$(HLDLL_OBJ_DIR)/monsters/ichthyosaur.o \
	$(HLDLL_OBJ_DIR)/monsters/islave.o \
	$(HLDLL_OBJ_DIR)/monsters/leech.o \
	$(HLDLL_OBJ_DIR)/systems/lights.o \
	$(HLDLL_OBJ_DIR)/gameplay/maprules.o \
	$(HLDLL_OBJ_DIR)/ai/monstermaker.o \
	$(HLDLL_OBJ_DIR)/ai/monsters.o \
	$(HLDLL_OBJ_DIR)/ai/monster_relationship_manager.o \
	$(HLDLL_OBJ_DIR)/ai/talk_companion_registry.o \
	$(HLDLL_OBJ_DIR)/ai/monster_combat.o \
	$(HLDLL_OBJ_DIR)/ai/monster_scheduler.o \
	$(HLDLL_OBJ_DIR)/ai/monster_sensors.o \
	$(HLDLL_OBJ_DIR)/ai/monsterstate.o \
	$(HLDLL_OBJ_DIR)/systems/mortar.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_mp5.o \
	$(HLDLL_OBJ_DIR)/monsters/nihilanth.o \
	$(HLDLL_OBJ_DIR)/ai/nodes_graph.o \
	$(HLDLL_OBJ_DIR)/ai/nodes_routing.o \
	$(HLDLL_OBJ_DIR)/ai/nodes_links.o \
	$(HLDLL_OBJ_DIR)/ai/nodes_debug.o \
	$(HLDLL_OBJ_DIR)/gameplay/observer.o \
	$(HLDLL_OBJ_DIR)/monsters/osprey.o \
	$(HLDLL_OBJ_DIR)/ai/pathcorner.o \
	$(HLCORE_OBJ_DIR)/plane.o \
	$(HLDLL_OBJ_DIR)/world/plats.o \
	$(HLDLL_OBJ_DIR)/core/player.o \
	$(HLDLL_OBJ_DIR)/core/player_input.o \
	$(HLDLL_OBJ_DIR)/core/player_inventory.o \
	$(HLDLL_OBJ_DIR)/core/player_physics.o \
	$(HLDLL_OBJ_DIR)/core/player_network.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_spraycan.o \
	$(HLDLL_OBJ_DIR)/monsters/monster_deadhev.o \
	$(HLDLL_OBJ_DIR)/gameplay/stripweapons.o \
	$(HLDLL_OBJ_DIR)/systems/revertsaved.o \
	$(HLDLL_OBJ_DIR)/systems/info_intermission.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_python.o \
	$(HLDLL_OBJ_DIR)/monsters/rat.o \
	$(HLDLL_OBJ_DIR)/monsters/roach.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_rpg.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_satchel.o \
	$(HLDLL_OBJ_DIR)/ai/schedule.o \
	$(HLDLL_OBJ_DIR)/gameplay/scripted.o \
	$(HLDLL_OBJ_DIR)/monsters/scientist.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_shotgun.o \
	$(HLCORE_OBJ_DIR)/skill.o \
	$(HLCORE_OBJ_DIR)/skill_manager.o \
	$(HLDLL_OBJ_DIR)/systems/sound.o \
	$(HLDLL_OBJ_DIR)/systems/sound_ambient.o \
	$(HLDLL_OBJ_DIR)/systems/sound_dsp.o \
	$(HLDLL_OBJ_DIR)/systems/sound_sentences.o \
	$(HLDLL_OBJ_DIR)/systems/sound_speaker.o \
	$(HLDLL_OBJ_DIR)/ai/soundent.o \
	$(HLDLL_OBJ_DIR)/gameplay/spectator.o \
	$(HLDLL_OBJ_DIR)/ai/squadmonster.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_snark.o \
	$(HLCORE_OBJ_DIR)/subs.o \
	$(HLDLL_OBJ_DIR)/ai/talkmonster.o \
	$(HLDLL_OBJ_DIR)/gameplay/teamplay_gamerules.o \
	$(HLDLL_OBJ_DIR)/gameplay/multiplay_gamerules.o \
	$(HLDLL_OBJ_DIR)/gameplay/gamerules_scoring.o \
	$(HLDLL_OBJ_DIR)/gameplay/gamerules_spawn.o \
	$(HLDLL_OBJ_DIR)/gameplay/gamerules_items.o \
	$(HLDLL_OBJ_DIR)/gameplay/singleplay_gamerules.o \
	$(HLDLL_OBJ_DIR)/gameplay/stats.o \
	$(HLDLL_OBJ_DIR)/systems/triggers_brush.o \
	$(HLDLL_OBJ_DIR)/systems/triggers_audio.o \
	$(HLDLL_OBJ_DIR)/systems/triggers_point.o \
	$(HLDLL_OBJ_DIR)/monsters/tentacle.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_tripmine.o \
	$(HLDLL_OBJ_DIR)/systems/turrets.o \
	$(HLCORE_OBJ_DIR)/util.o \
	$(HLCORE_OBJ_DIR)/util_trace.o \
	$(HLCORE_OBJ_DIR)/util_saverestore.o \
	$(HLCORE_OBJ_DIR)/util_math.o \
	$(HLCORE_OBJ_DIR)/util_entity.o \
	$(HLCORE_OBJ_DIR)/util_debug.o \
	$(HLDLL_OBJ_DIR)/systems/vehicle.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_base.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_registry.o \
	$(HLDLL_OBJ_DIR)/weapons/weapon_box.o \
	$(HLDLL_OBJ_DIR)/weapons/player_item_base.o \
	$(HLDLL_OBJ_DIR)/world/world.o \
	$(HLDLL_OBJ_DIR)/world/xen.o \
	$(HLDLL_OBJ_DIR)/monsters/zombie.o

HLWPN_OBJS = \
	$(HLDLL_OBJ_DIR)/weapons/weapon_glock.o

PM_OBJS = \
	$(PM_OBJ_DIR)/pm_shared.o \
	$(PM_OBJ_DIR)/pm_step.o \
	$(PM_OBJ_DIR)/pm_move_ground.o \
	$(PM_OBJ_DIR)/pm_move_air.o \
	$(PM_OBJ_DIR)/pm_move_water.o \
	$(PM_OBJ_DIR)/pm_ladders.o \
	$(PM_OBJ_DIR)/pm_duck.o \
	$(PM_OBJ_DIR)/pm_hull.o \
	$(PM_OBJ_DIR)/pm_math.o \
	$(PM_OBJ_DIR)/pm_debug.o

GAME_SHARED_OBJS = \
	$(GAME_SHARED_OBJ_DIR)/voice_gamemgr.o

all: dirs hl.$(SHLIBEXT)

dirs:
	-mkdir -p $(BUILD_OBJ_DIR)
	-mkdir -p $(HLDLL_OBJ_DIR)
	-mkdir -p $(HLDLL_OBJ_DIR)/items
	-mkdir -p $(HLDLL_OBJ_DIR)/systems
	-mkdir -p $(HLDLL_OBJ_DIR)/weapons
	-mkdir -p $(HLDLL_OBJ_DIR)/monsters
	-mkdir -p $(HLDLL_OBJ_DIR)/gameplay
	-mkdir -p $(HLDLL_OBJ_DIR)/ai
	-mkdir -p $(HLCORE_OBJ_DIR)
	-mkdir -p $(HLWPN_OBJ_DIR)
	-mkdir -p $(PM_OBJ_DIR)
	-mkdir -p $(GAME_SHARED_OBJ_DIR)
	-mkdir -p $(HLDLL_OBJ_DIR)/world

hl.$(SHLIBEXT): $(HLDLL_OBJS) $(HLWPN_OBJS) $(PM_OBJS) $(GAME_SHARED_OBJS)
	$(CC) $(LDFLAGS) $(SHLIBLDFLAGS) -o $(BUILD_DIR)/$@ $(HLDLL_OBJS) $(HLWPN_OBJS) $(PM_OBJS) $(GAME_SHARED_OBJS)
ifeq ($(CREATE_OUTPUT_DIRS),1)
	mkdir -p $(HL_OUTPUT_DIR)/dlls
endif
	$(P4_EDIT_START) $(HL_OUTPUT_DIR)/dlls/hl.$(SHLIBEXT) $(P4_EDIT_END)
	cp $(BUILD_DIR)/$@  $(HL_OUTPUT_DIR)/dlls/hl.$(SHLIBEXT)
	./gendbg.sh $(HL_OUTPUT_DIR)/dlls/hl.$(SHLIBEXT)

$(HLWPN_OBJ_DIR)/%.o : $(HLWPN_SRC_DIR)/%.cpp
	$(DO_HLWPN_CC)

$(HLDLL_OBJ_DIR)/systems/%.o : $(HLDLL_SRC_DIR)/systems/%.cpp
	$(DO_HLDLL_CC)

$(HLDLL_OBJ_DIR)/weapons/%.o : $(HLDLL_SRC_DIR)/weapons/%.cpp
	$(DO_HLDLL_CC)

$(HLDLL_OBJ_DIR)/items/%.o : $(HLDLL_SRC_DIR)/items/%.cpp
	$(DO_HLDLL_CC)

$(HLDLL_OBJ_DIR)/world/%.o : $(HLDLL_SRC_DIR)/world/%.cpp
	$(DO_HLDLL_CC)



$(HLDLL_OBJ_DIR)/ai/%.o : $(HLDLL_SRC_DIR)/ai/%.cpp
	$(DO_HLDLL_CC)

$(HLDLL_OBJ_DIR)/monsters/%.o : $(HLDLL_SRC_DIR)/monsters/%.cpp
	$(DO_HLDLL_CC)

$(HLDLL_OBJ_DIR)/gameplay/%.o : $(HLDLL_SRC_DIR)/gameplay/%.cpp
	$(DO_HLDLL_CC)

$(HLDLL_OBJ_DIR)/%.o : $(HLDLL_SRC_DIR)/%.cpp
	$(DO_HLDLL_CC)

$(HLCORE_OBJ_DIR)/%.o : $(HLCORE_SRC_DIR)/%.cpp
	$(DO_HLDLL_CC)

$(PM_OBJ_DIR)/%.o : $(PM_SRC_DIR)/%.c
	$(DO_PM_CC)

$(GAME_SHARED_OBJ_DIR)/%.o : $(GAME_SHARED_SRC_DIR)/%.cpp
	$(DO_GAME_SHARED_CC)

clean:
	-rm -rf $(GAME_SHARED_OBJ_DIR)
	-rm -rf $(PM_OBJ_DIR)
	-rm -rf $(HLWPN_OBJ_DIR)
	-rm -rf $(HLDLL_OBJ_DIR)
	-rm -rf $(HLCORE_OBJ_DIR)
	-rm -f hl_$(ARCH).$(SHLIBEXT)
